title: "Aizaz Sharif"
author: "Aizaz Sharif"
description: "Portfolio"
more: "read more »"
url: "https://aizazsharif.github.io/"
baseurl: "/"
paginate: 2
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: false

navigation:
  - index.html
  - archive.html
  - about.md

comments:
  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - twitter: "https://twitter.com/AizazSharif420"
  - github: "https://github.com/AizazSharif"
  - envelope: "p177003@nu.edu.pk"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate, jekyll-seo-tag]

theme: jekyll-theme-cayman