# Site setings
name: Aizaz Sharif
bio: Computer Science Major, Researcher, Developer, and Gamer
meta_description: 'Computer Science Major, Researcher, Developer, and Gamer'

favicon: 'assets/images/favicon.ico'
baseurl: /
production_url: http://aizazsharif.github.io
disqus: 'justgoodthemes'
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: UA-121645203-1


# Author
author:
  name: 'Aizaz Sharif'
  image: 'assets/images/profile.jpg'
  bio: 'Computer Science Major, Researcher, Developer, and Gamer'

# Contact form setings
email: aizazsharif@gmail.com
contact_page_description: ""
thankyou_page_description: "Your message has been successfully sent."

# Social links
twitter: 'AizazSharif420'
#facebook: 'username'
github: 'AizazSharif'
#codepen: 'username'
#dribbble: 'username'
medium: '@AizazSharif420'
instagram: 'aizaz_sharif_420'
#pinterest: 'username'
linkedin: 'aizazsharif'
#producthunt: '@username'

# Navigation
navigation:
  - text: About
    url: /about
  - text: Style Guide
    url: /style-guide
  - text: Contact Me
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
