# Site settings
exclude: [README.md,example1.md,example2.md]
title: Aizaz Sharif
email: aizaz@simula.no
github: AizazSharif
twitter: AizazSharif420
scholar_id: luceUvgAAAAJ&hl
instagram: aizaz_sharif
researchgate: Aizaz_Sharif
linkedin: aizazsharif

description: > # this symbol means ignore newlines until "baseurl:"
    Computer Science Major, Researcher, Software Engineer, and a Philomath
baseurl: "" # keep blank unless you're using sub-paths
url: "https://aizazsharif.github.io" # the base hostname & protocol for your site
#paginate: 3

# you can also declare arbitrary key-value data here
uva_url_lena: "https://www.simula.no/people/aizaz"
#uva_url_main: "https://www.illc.uva.nl"
#edn_nlp_people: "https://edinburghnlp.inf.ed.ac.uk/index.php/people/"
#edn_nlp_main: "http://edinburghnlp.inf.ed.ac.uk"
#school_of_informatics: "https://www.ed.ac.uk/informatics"
yandex_research_people: "http://www.nccs.pk/"
#yandex_research_main: "https://research.yandex.com"

ivan_page: "https://www.simula.no/people/dusica"
rico_page: "https://simula.no/people/arnaud"


# Build settings
markdown: kramdown
